apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: insuretech-app-sm
  namespace: default
  labels:
    release: prometheus-operator
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: insuretech-app